Repository BadaWikiDev/VientoEngine, pull requests merged in 2021-01, with the labels that each got.

#1 500, 405 오류 수정
  app.py
Labels: 버그 (Bug)

#2 공식 사이트 URL수정
  README.md
Labels: 개선 (Improving)

#3 해싱 알고리즘 추가
  app.py
  requirements.txt
  route/tool/tool.py
Labels: 개선 (Improving), 기능 (Function), 추가 (Add)

#4 500 오류 수정
  app.py
Labels: 버그 (Bug)
